### ISSUE TITLE
how can i get the file “stackoverflow_data.csv” ？

### ISSUE THREAD

**Issue by Ngwind** [qxf2/what-do-i-do-next#5]
i run the script which name is setup_neo4j_db.py，but it is error ： 

`FileNotFoundError: [Errno 2] No such file or directory: '/what-do-i-do-next/data/stackoverflow_data.csv'`

**Comment by Annapooraniqxf2** [comment]
> i run the script which name is setup_neo4j_db.py，but it is error ：
> 
> `FileNotFoundError: [Errno 2] No such file or directory: '/what-do-i-do-next/data/stackoverflow_data.csv'`

Hi Ngwind,

We have collected data related to our projects with technologies , view counts, answer counts and related tags from stackoverflow. We didnt push that file here. That's why you are getting No such file or directory error.

**Comment by qxf2** [comment]
@Ngwind can you please email me (mak@qxf2.com) and I can share our csv with you. It is more than a gig of data.
